---
- name: install libselinux-python
  yum: name=libselinux-python-2.0.94-5.8.el6.{{ common.arch }}
  tags: ansible_deps

- name: install MySQL-python
  yum: name=MySQL-python-1.2.3-0.3.c1.1.el6.{{ common.arch }}
  tags: ansible_deps

- name: install git
  yum: name=git state=latest
  tags: ansible_deps

- name: install vim
  yum: name=vim state=latest
  tags: ansible_deps