---
- name: install libselinux-python
  yum: name=libselinux-python-2.0.94-5.8.el6.{{ common.arch }}

- name: install git
  yum: name=git state=latest

- name: install vim
  yum: name=vim state=latest